### PR TITLE
Enable ReactPHP Support

### PR DESCRIPTION
**Pull request by therealmikz**
I needed to use Ratchet (cboden/Ratchet) and react-amqp (jcook/react-amqp) along with daemon-bundle. Both of those libraries use great tool called ReactPHP (http://reactphp.org/) - it's non-blocking I/O in PHP.
It was impossible because daemon-bundle was using locking while loop, so React couldn't work with its event loops.

I've added new class ReactCommand that extends AbstractCommand (AbstractCommand contains most of old ExtendCommand code). I also left old ExtendCommand compatible with previous version so all of daemons written regular way should work without problems (no react needed for them to work).

To use new features, you need to extend ReactCommand instead of ExtendCommand and declare prepareLoop(React\EventLoop\LoopInterface $loop) method that creates daemon logic as periodicTimer in event loop.

Feel free to contact me if you have any questions, I'll watch this PR for new comments.

### CODE REVIEW

**Comment by cryptiklemur** [comment]
Mind throwing your name/email in the author section in composer.json?

**Comment by cryptiklemur** [comment]
Looks good otherwise, Just a heads up, im gonna go ahead and try to convert this bundle to be PSR compliant after merging this in. I should've done it before, but thats my bad.

**Comment by therealmikz** [comment]
Ok, I'm in authors now.
BTW, test these changes before merging, I'm pretty sure that they are compatible with old version but nobody's perfect :)

Oh, and one more thing: is there any reason for logging events everytime they're triggered? I'm afraid that this can lead to really big logfiles.

**Comment by cryptiklemur** [comment]
Honestly, I'm not using this anywhere i can test it. I'm going to just have to fix issues as they come up. I switched everything to PSR standards as well now, and added your `true !== $this->test` check back in. 

As for the logging, maybe? but I'd hope to think that people would be able to figure out logrotate or something to automatically prune their logs, might make sense to have debug levels, and make that configurable

**Pull request merged**
